steps:
  - command: echo "build things"
    if: build.branch == 'main'
  
  - block: "Deploy to Staging?"
    branches: "!main"

  - wait
  
  - command: echo "deploy things"
    
  - wait
    
  - command: echo "clean things up"
    if: build.branch == 'main'
